services:
  - type: web
    name: yt-pitch-server
    plan: free
    env: node
    rootDir: server
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: YOUTUBE_DL_SKIP_PYTHON_CHECK
        value: "1"
      - key: PORT
        value: 3001
